### ISSUE TITLE
Tests für Service layer

### ISSUE THREAD

**Issue by raphiz** [Excape/mste-miniprojekt#6]
Schreiben Sie die geforderten Tests für den Service-Layer

**Comment by jmatj** [comment]
Offene Tests in ServiceTestBase.cs
- [x] UpdateReservationTest
- [x] UpdateAutoWithOptimisticConcurrencyTest
- [x] UpdateKundeWithOptimisticConcurrencyTest
- [x] UpdateReservationWithOptimisticConcurrencyTest
